# Generated by Django 4.0.4 on 2022-04-18 00:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abbynormal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storylist',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='my_storylists', to=settings.AUTH_USER_MODEL),
        ),
    ]
