# Generated by Django 4.0.4 on 2022-04-18 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abbynormal', '0002_storylist_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createstory',
            name='state',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='createstory',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='createstory',
            name='country',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='storylist',
            name='user_id',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='my_storylists', to=settings.AUTH_USER_MODEL),
        ),
    ]
