# Generated by Django 4.0.4 on 2022-04-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbynormal', '0003_createstory_state_alter_createstory_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createstory',
            name='story_title',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.DeleteModel(
            name='StoryList',
        ),
    ]
