# Generated by Django 4.0.4 on 2022-04-26 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbynormal', '0005_alter_createstory_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstory',
            name='story_title',
            field=models.TextField(default=None),
        ),
    ]
