# Generated by Django 4.0.4 on 2022-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbynormal', '0006_alter_createstory_story_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.TextField(default=None),
        ),
    ]
