# Generated by Django 4.0.4 on 2022-04-27 14:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('abbynormal', '0007_alter_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='uploader',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_images', to=settings.AUTH_USER_MODEL),
        ),
    ]
