# Generated by Django 4.0.4 on 2022-04-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbynormal', '0008_alter_images_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.TextField(default=None, null=True),
        ),
    ]
