# Generated by Django 4.0.4 on 2022-04-29 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('abbynormal', '0010_alter_images_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createstory',
            name='my_image',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stories', to='abbynormal.images'),
        ),
    ]
