# Generated by Django 4.0.4 on 2022-05-01 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abbynormal', '0011_createstory_my_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createstory',
            name='my_image',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
